New autoassign parameter for agent category belonging
thekordy/ticketit pull request #309
Opened 2017-03-07 08:49 UTC by xaviqv

This update adds a new parameter "autoassign" that it's stored in the agent_category pivot table and it's meant to solve our particular scenario, where I have at the moment two categories:

1. The first one, is a category where I have one agent that has to check all new tickets:
- If it's not for her, or when It's needed, she has to be able to assign that ticket to other agents in the category (me or my boss)

2. The second one is the IT main category:
- We want to receive new tickets notification in one of our department shared mail accounts, so everyone can be noticed about new tickets
- Later, we want to distribute these tickets manually to whom is the best agent on each case, at least for the first support step

I've improved eloquent queries a bit. If it's worth to publish this then I'll create new translation fields and apply on the modified blade template

Comments and suggestions are all welcome!

2017-03-27 20:48 UTC, thekordy requested changes

2017-03-27 20:48 UTC, thekordy commented on src/Views/admin/agent/index.blade.php
> +	<script src="{!! asset('vendor/ticketit/js/agent_index.js') !!}"></script>
Use instead:
```blade
@section('footer')
    <script type="text/javascript">
        $(function(){
            $('.jquery_agent_cat').click(function(){
                var checked=$(this).hasClass('checked');
                if (checked){
                    $(this).removeClass('checked');
                    $('#'+$(this).attr('id')+"_auto").prop('checked',false).prop('disabled','disabled');
                } else {
                    $(this).addClass('checked');
                    $('#'+$(this).attr('id')+"_auto").prop('checked','checked').prop('disabled',false);
                }
            });
        });
    </script>
@endsection
```

2017-03-27 20:48 UTC, thekordy commented on src/Views/admin/agent/index.blade.php
> +									<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
Can't submit the form, please check it.

2017-03-27 20:48 UTC, thekordy commented on src/Views/admin/agent/index.blade.php
> +										<thead><th>Category</th>
No plain words please,  use the translation

2017-03-27 20:48 UTC, thekordy commented on src/Views/admin/agent/index.blade.php
> +								  <h3 class="pull-left">Agent: {{ $agent->name }}</h3>
No plain words please, use the translation

2017-03-27 20:48 UTC, thekordy commented on src/Views/admin/agent/index.blade.php
> +									<h4 class="modal-title" id="myModalLabel">Agent categories</h4>
No plain words please, use the translation

2017-03-27 20:48 UTC, thekordy commented on src/Views/admin/agent/index.blade.php
> +										<th>Active</th>
No plain words please, use the translation

2017-03-27 20:48 UTC, thekordy commented on src/Views/admin/agent/index.blade.php
> +										<th>Autoassign enabled</th></thead>
No plain words please, use the translation

2017-03-28 09:30 UTC, xaviqv commented
I've done all the changes. The form couldn't be submitted without publishing the .js file. Sorry for not specifying that.

I knew that all translation fields were pending and I'm sorry If I didn't explain well the status of this pull request as it gave you extra work. Next time I hope to be more clear about pending changes before PR approval.

Thanks for you feedback!

2017-05-08 16:16 UTC, xaviqv commented
Is there any requested change pending in this PR or anything else that has to be edited? Have you checked it out after my updates? Thank you!

2017-05-09 11:57 UTC, xaviqv commented on src/Views/admin/agent/index.blade.php
> +									<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
Corrected on 28 Mar.

2017-05-09 12:04 UTC, xaviqv reviewed
I think there are no pending modifications after my updates

2017-05-27 14:00 UTC, thekordy commented
not ready for production, sorry.

2017-05-27 14:00 UTC, closed without merging