Attachments: files can be attached for ticket and comments
thekordy/ticketit pull request #321
Opened 2017-03-22 13:04 UTC by nikolay-zakharov

2017-03-24 08:38 UTC, xaviqv commented
I've tested you pull request and it works great! For me it is a must for this project.

I have some suggestions of improvements for attached files:

**In ticket list**
- To have an icon indicating tickets with attached files. Also with the attached files count.
- An extra to the last point would be to be able to get the files directly form the ticket list. For this, I've got in mind two approaches: A kind of bootstrap based [dropdown menu](https://www.w3schools.com/bootstrap/bootstrap_dropdowns.asp) or a bootstrap [popover](https://www.w3schools.com/bootstrap/bootstrap_popover.asp) or using the [Datatables child rows](https://datatables.net/examples/api/row_details.html).

**In the ticket or comment form**
- After selecting many files, ability to discard them individually, like scripts [like jQuery file upload do](https://i.stack.imgur.com/qLbyQ.png).

**In the ticket card**
- Ability to discard already attached files on ticket or comment
- To have a list of all the ticket attached files near the ticket fields at the beggining.
- To view thumbnails of the attached files that are images. In this case, open the image directy instead of downloading it

**Related settings**
- Setting for allowed file extensions
- Setting for max number of attached files for each post (even new ticket or comment).
- Maybe another setting for the whole ticket attached files count? Although it doesn't make sense to me
- Setting for max file size

2017-03-25 12:33 UTC, thekordy commented
@nikolay-zakharov I like it, well done :+1:  

I must say I agree with @xaviqv mentioned Related settings:
>>Setting for allowed file extensions
Setting for max number of attached files for each post (even new ticket or comment).
Maybe another setting for the whole ticket attached files count? Although it doesn't make sense to me
Setting for max file size

I am approving this PR, to make it available for you and others to work on these points.

2017-03-27 20:42 UTC, thekordy requested changes

2017-03-27 20:42 UTC, thekordy commented on src/Controllers/TicketsController.php
> +                    $ticketQuery->agentUserTickets($user->id);
I think this should be related to the configured option 'agent_restrict', if agents are not restricted, let them download any file.

2017-03-27 20:48 UTC, thekordy commented on src/Migrations/2017_03_21_144731_add_ticketit_attachments.php
> +            $table->unsignedInteger('comment_id')->nullable();
Fine by me, but I think if you convert this to a polymorphic relationship, will make your model reusable. just a thought.

2017-05-04 20:54 UTC, closed without merging