New agent and owner menu
thekordy/ticketit pull request #322
Opened 2017-03-23 08:02 UTC by xaviqv

For a more scalable environment, I have made the following changes:
- For Admin or Agent with agent_restrict=0: View new panel with lists of all agents including ticket counts. You can now choose an agent and tickets assigned to him/her will be listed (*1)
- For anyone except user: View new Owner buttons, where you can click and view in different lists the tickets I have created and the tickets that are assigned to me.
- Different title for tickets list deppending on chosen agent or owner.

(*1) Before this update, agent sees a list mixing the tickets where is the assigned agent and the tickets where he/she is the owner. In the parameter "agent_restrict", there is the following description: Restrict agents access to only their assigned tickets. With this in mind, with this update, any agent with agent_restrict=0 may see any other agent in the categories where current agent is and their tickets in these categories

Internal highlight changes:
- New scopes for Agent and Ticket models. Specially scopeVisible(), that filters any of these models deppending on user permissions
- Two new session variables 'ticketit_filter_agent' and 'ticketit_filter_owner' managed in new FiltersController

Any feedback or suggestions are welcome!

2017-03-23 22:38 UTC, balping commented
Wow seems like a lot of work. I don't know what @thekordy 's plans are with the 0.2 branch, but I hope this doesn't get wasted.

2017-03-23 22:41 UTC, FusionDesign commented
I was actually just looking at this prior to opening my issue. That's why I got a bit confused. I'm still pulling this in to check it out.

2017-03-24 00:35 UTC, FusionDesign commented
Going to take a quick break. I just went through 3 laravel versions before I realized 0.2 was 5.4 compatible all along -.-

Got one PR up for this, just a quick bug found.

2017-03-24 01:38 UTC, FusionDesign commented
I spun up a User factory and generated a fresh install to test this out. I purposely wanted to test how your UX would respond to many Agents for bigger user bases. This is what it looks like:
![current](https://cloud.githubusercontent.com/assets/3439293/24276972/adb8ff54-1010-11e7-8d3b-9b88ad2466b4.png)

This is what I propose:
![proposed](https://cloud.githubusercontent.com/assets/3439293/24277022/0515a0ae-1011-11e7-9cc6-c2df439b6188.png)


Thoughts? I'm just trying to get back into what the branch was like after I left before I move forward with 2.1 branch. This is helping.

2017-03-24 07:58 UTC, xaviqv commented
The main idea for me and this "agents menu" is to have the list filtered as with few clicks as possible, to have a daily work quick and easy. Anyway, although I'm sure about this pull request because for me these filters are a must, I'm not convinced about it's presentation. My boss also is not convinced about it, but for the fact of having a new panel that takes space on screen to the ticket list.

I was also doubting to have this menu in a dropdown. Finally I opted for the full menu because it fits with our environment (6 agents), but to be more flexible maybe there would be better to have a new setting to let admin choose between the full menu or the dropdown.

We have planned two more filters that can alter the conclusions about the best option: 
- Category filter: The same of the agent filter. It can be also a list of buttons or a dropdown
- Tags filter: There will be somewhere in admin panel a menu to manage different tags for each category. Any ticket would have many tags, and this is going to be shown on the ticket list and card. Also it will be then a needing to filter this as needed on ticket list.

There can be the possibility of having firstly the Category filter, so if you choose a category, then the agent list (even though you are an admin) will show only the ones that belong to it.

Anyway, for now I'm almost sure the best approach is to have a setting for each filter to let admin choose to show any of them in a dropdown or separate buttons. Maybe this is an enough flexible approach that can fit on any environment. Another one would be automatically having separate buttons or dropdown deppending on agent count. What do you think?

Also, @FusionDesign , why have you positioned the Owner menu underneath the ticket list? Doesn't look bad in the screenshot but you have there only few tickets listed. I've to say that I'm neither convinced on my Owner menu original position nor display, but the advantage of having it in the ticket list title panel is that it's not taking screen space.

2017-03-25 12:42 UTC, thekordy commented
@xaviqv I like the idea, but as @FusionDesign said, it won't work for bigger data sets. What about select2 jquery plugin?

2017-03-27 13:44 UTC, xaviqv commented
Here you have it @thekordy . I've added a conditional on view to still view separate buttons when having 4 or less visible agents. This makes the settings I have listed before an optional add-on.

2017-03-27 20:33 UTC, thekordy commented
Just reviewed the controller, Models and views not reviewed yet.

2017-03-27 20:35 UTC, thekordy commented
Some issues with assets and javascript loading

![screenshot from 2017-03-27 22 34 18](https://cloud.githubusercontent.com/assets/11343048/24376839/9cf0b68c-133d-11e7-80ff-73dd56025361.jpeg)

2017-03-27 20:38 UTC, thekordy requested changes
Need more work

2017-03-27 20:38 UTC, thekordy commented on src/Controllers/FiltersController.php
> +            abort(404);
No need for any 404 exception

2017-03-27 20:38 UTC, thekordy commented on src/routes.php
> +        Route::get("$main_route_path/filter/{filter}/{value}", 'Kordy\Ticketit\Controllers\FiltersController@manage');
What about using the filter method from within TicketsController index method? no need for a separate route

2017-03-27 20:38 UTC, thekordy commented on src/Controllers/FiltersController.php
> +            if ($filter == 'agent') {
Shouldn't we validate the permissions first? Users can't filter

2017-03-27 20:38 UTC, thekordy commented on src/Controllers/TicketsController.php
> +        if (session('ticketit_filter_agent') != '') {
Shouldn't we validate the permissions first? Users can't filter

2017-03-27 20:38 UTC, thekordy commented on src/Controllers/TicketsController.php
> +            $collection = $collection->whereHas('agent', function ($q) use ($agentid) {
can use `agentTickets($agentid)` scope instead of `whereHas`, I think that would be more optimized

2017-03-27 20:38 UTC, thekordy commented on src/Controllers/TicketsController.php
> +            $collection = $collection->UserTickets(auth()->user()->id);
better to be restricted to the code conventions, use `userTickets()` instead of `UserTickets()`

2017-03-27 20:38 UTC, thekordy commented on src/Controllers/TicketsController.php
> +        $collection = Ticket::ListComplete($complete);
I think the name is some how misleading, you organized this function very well, but what about more describable name? getList or something like that would work.

2017-03-27 20:38 UTC, thekordy commented on src/Controllers/TicketsController.php
> +            $counts['total_agent'] = Ticket::ListComplete($complete)->Visible()->count();
for code conventions `Ticket::listComplete($complete)->visible()->count()`

2017-03-27 20:38 UTC, thekordy commented on src/Controllers/TicketsController.php
> +    public function ticketCounts($complete)
How many queries does this function run?

2017-03-28 06:59 UTC, xaviqv commented on src/Controllers/FiltersController.php
> +            abort(404);
Ok. Maybe would It be better to just redirect back?

Also I've tested what you pasted about not found files.  The routes points at "public" Laravel folder, so publishing is needed for them.

2017-03-28 07:21 UTC, xaviqv commented on src/Controllers/TicketsController.php
> +        $collection = Ticket::ListComplete($complete);
In this case I tried to adapt to current functionality. The $complete values can be true or false, so the idea was to read it as "list complete -> true" or "list complete -> false".

Another alternative approach following your proposal could also be scopeList($list) where $list can be "active" or "complete".

For getList($var) are you thinking $var like the current $complete is, or like the $list I propose? Anyway, please tell me what do you prefer and I'm going to work on it.

2017-03-28 07:27 UTC, xaviqv commented on src/routes.php
> +        Route::get("$main_route_path/filter/{filter}/{value}", 'Kordy\Ticketit\Controllers\FiltersController@manage');
I'm sorry that I don't know how to do exactly what you suggest to. Do you mean to move the current "manage()" method from inside FiltersController to TicketsController with a name, for example, manageFilter() with the same current functionality inside?

For me it's ok to make this change.

2017-03-28 07:32 UTC, xaviqv commented on src/Controllers/TicketsController.php
> +            $collection = $collection->whereHas('agent', function ($q) use ($agentid) {
Ok, changed it. It's a mistake :(

2017-03-28 07:46 UTC, xaviqv commented on src/Controllers/TicketsController.php
> +            $collection = $collection->UserTickets(auth()->user()->id);
Didn't know that at all! Corrected It. I've seen also that in most cases in my code I used scopes with first capital letter. I corrected also all the ones I have spotted, like Visible() or AgentTickets().

2017-03-28 07:57 UTC, xaviqv commented on src/Controllers/TicketsController.php
> +    public function ticketCounts($complete)
The min is 2 (for agent with agent_restrict=1) and the max is 4 (for an admin).

Screenshot from debugbar and admin:
![image](https://cloud.githubusercontent.com/assets/25639840/24394574/c6f33626-139c-11e7-9428-4170e9d0f632.png)

2017-03-28 09:12 UTC, thekordy commented on src/routes.php
> +        Route::get("$main_route_path/filter/{filter}/{value}", 'Kordy\Ticketit\Controllers\FiltersController@manage');
Sorry, I meant to call it from within the index method @ TicketsController

2017-05-27 13:57 UTC, thekordy commented
Thank you for your contribution, but it's not ready for production, sorry.

2017-05-27 13:57 UTC, closed without merging