Bug correction: Don't allow empty html or whitespaces in content
thekordy/ticketit pull request #326
Opened 2017-03-27 10:42 UTC by xaviqv

There are currently some errors regarding empty content in several fields:

**Subject**
- Whitespaces in the beginning or the end of are treated as valid characters.

**Ticket description, Ticket comment**
- Whitespaces in the beginning or the end are treated as valid characters.
- Not visible HTML (for example empty rows) are treated as valid characters.
- Validation required lenght is based on html input

Corrections applied:
- Input trimming (both for subject and content)
- Content validation now uses the purified content without html tags. This prevents also accepting content that includes a screenshot without any text before or after it.

2017-03-27 20:37 UTC, thekordy reviewed
I think a minor trim to the setPurifiedContent method would solve it all

2017-03-27 20:37 UTC, thekordy commented on src/Traits/Purifiable.php
> -    public function setPurifiedContent($rawHtml)
Don't break the API please

2017-03-27 20:37 UTC, thekordy commented on src/Controllers/CommentsController.php
> +        $a_content = $this->purifyHtml($request->get('content'));
please use meaningful names

2017-03-27 20:37 UTC, thekordy commented on src/Controllers/CommentsController.php
> -        $comment->setPurifiedContent($request->get('content'));
Why  not that API?

2017-03-27 20:37 UTC, thekordy commented on src/Controllers/TicketsController.php
> +        $a_content = $this->purifyHtml($request->get('content'));
meaningful names please

2017-03-27 20:37 UTC, thekordy commented on src/Controllers/TicketsController.php
> -        $ticket->setPurifiedContent($request->get('content'));
Why not use the current purify trait?

2017-03-27 20:37 UTC, thekordy commented on src/Controllers/TicketsController.php
> +        //return redirect()->action('\Kordy\Ticketit\Controllers\TicketsController@index');
why?

2017-03-27 20:40 UTC, thekordy requested changes

2017-03-27 20:40 UTC, thekordy commented on src/Traits/Purifiable.php
> -        $this->html = Purifier::clean($rawHtml, Setting::grab('purifier_config'));
Wouldn't a trim here be enough?

2017-03-28 09:39 UTC, xaviqv commented on src/Controllers/CommentsController.php
> -        $comment->setPurifiedContent($request->get('content'));
I though that for performance reasons, having already the purified code before validate(), It was not needed to run it again.

2017-03-28 09:59 UTC, xaviqv commented on src/Controllers/TicketsController.php
> +        $a_content = $this->purifyHtml($request->get('content'));
Maybe would be better something like "getPurifiedHtml()?"

2017-03-28 10:02 UTC, xaviqv commented on src/Controllers/TicketsController.php
> +        //return redirect()->action('\Kordy\Ticketit\Controllers\TicketsController@index');
I'm sorry. It was a modification for testing only!

2017-03-28 10:09 UTC, xaviqv commented on src/Traits/Purifiable.php
> -        $this->html = Purifier::clean($rawHtml, Setting::grab('purifier_config'));
In my testings I started with that simple trim(). I don't know why, but It didn't make any effect on output, both for subject or content. Then I found out the parameter regarding to new rows, tabs... etc " \t\n\r\0\x0B". It also didnt make effect on the output. I though it was that somewhere in the code, the spaces in the form fields are identified or converted to something else.

Finally, the difference was adding "chr(0xC2).chr(0xA0)" that I found on [one php.net trim() comment](http://php.net/manual/en/function.trim.php#98812). I keeped also the " \t\n\r\0\x0B" string to clean the input in other cases that I didn't foresee.

2017-05-27 14:01 UTC, thekordy commented
not ready for production, sorry.

2017-05-27 14:01 UTC, closed without merging

2017-05-27 14:05 UTC, roni-estein commented
Thank you!
Spark by Readdle