Category filter
thekordy/ticketit pull request #339
Opened 2017-04-21 10:39 UTC by xaviqv

Added category filter on the same header menu. About this update:
- Listed agents depending on filtered category.
- Ticket list titles specify category, agent and owner (if any of these is chosen).
- Category column disappears when category filter is in use

2017-05-25 01:34 UTC, munkhsaikhans approved these changes

2017-05-25 14:45 UTC, balping requested changes
I haven't really reviewed the blade files, but the design is ok, I guess

2017-05-25 14:45 UTC, balping commented on src/Controllers/TicketsController.php
> +        $collection = Ticket::listComplete($complete);
`$collection` doesn't really describe the purpose of this variable.

2017-05-25 14:45 UTC, balping commented on src/Models/Agent.php
> +            })->orderBy('name', 'ASC');
Code duplication

2017-05-25 14:45 UTC, balping commented on src/Models/Agent.php
> +            return $query->VisibleForAgent(auth()->user()->id);
Let's stick to the convention of having the first letter of scopes lower case. Applies elsewhere too

2017-05-25 14:45 UTC, balping commented on src/Models/Ticket.php
> +    public function scopeInCategory($query, $id = null)
Should we move these whole bunch of scopes to a trait maybe?

2017-05-25 14:45 UTC, balping commented on src/Views/shared/assets.blade.php
> +<link rel="StyleSheet" href="{{asset('vendor/ticketit/css/select2.min.css')}}">
I'd prefer pulling this jquery plugin via cdn, as we do for codemirror, summernote and fontawesome. No need to keep a copy of this library in this repo + it's easier to upgrade.

2017-05-25 14:48 UTC, balping commented on src/Controllers/TicketsController.php
> +        $collection = Ticket::listComplete($complete);
I can see it was like that before, but maybe it's time to change it.

2017-05-27 13:56 UTC, thekordy commented
A lot of issues, let's move on.

2017-05-27 13:56 UTC, closed without merging