Refactor
thekordy/ticketit pull request #492
Opened 2018-08-27 19:33 UTC by imanghafoori1

2018-08-27 19:58 UTC, thekordy commented
Good to think about refactoring the code, and great from you to share it :+1:  .. Thanks for your contributions.

2018-08-27 19:59 UTC, thekordy requested changes

2018-08-27 19:59 UTC, thekordy commented on src/TicketitServiceProvider.php
> +            app(CommentObserver::class)->creating();
I think this should be `Comment::observe(CommentObserver::class);` ... see balping [comment](https://github.com/thekordy/ticketit/pull/491#issuecomment-416339807)

2018-08-27 19:59 UTC, thekordy commented on src/TicketitServiceProvider.php
> +            $ticketObserver = app(TicketObserver::class);
Same as above

2018-08-27 19:59 UTC, thekordy commented on src/TicketitServiceProvider.php
> +            $ticketObserver->created();
same as above

2018-08-27 19:59 UTC, thekordy commented on src/ModelsObservers/CommentObserver.php
> +        Comment::creating(function ($comment) {
I think we don't need to listen the event inside the observer, already done in the Service Provider, I believe we should remove that line, and get enough with the callback content.

May be:
```php
public function creating(Comment $comment)
{
    if (Setting::grab('comment_notification')) {
        $notification = new NotificationsController();
        $notification->newComment($comment);
     }
}
```

2018-08-27 19:59 UTC, thekordy commented on src/ModelsObservers/TicketObserver.php
> +        Ticket::created(function ($ticket) {
same as above

2018-08-27 19:59 UTC, thekordy commented on src/ModelsObservers/TicketObserver.php
> +        Ticket::updating(function ($modified_ticket) {
same as above

2018-08-28 07:02 UTC, imanghafoori1 commented on src/TicketitServiceProvider.php
> +            app(CommentObserver::class)->creating();
These classes I have created, have nothing to do with laravel model observers.
They are just normal php classes to put some code within them.
Actually I want my PR to be as understandable as possible for you. so you can accept them

2018-08-28 07:03 UTC, imanghafoori1 commented
I just wanted to put the code somewhere else and call it.
The main goal is to make the the whole package ready to have unit tests.

2018-09-02 16:20 UTC, balping commented
I agree that the service provider now is a mess, but how does extracting these make it more testable?

2018-09-02 18:33 UTC, imanghafoori1 commented
Since we are resolving the new classes through the IOC container (app() helper function) now we can mock them and replace them with mock objects.

2020-04-21 15:17 UTC, closed without merging